name: Terraform Cloud Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=infra/terraform init

      - name: Terraform Plan
        run: terraform -chdir=infra/terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=infra/terraform apply -auto-approve
